
### DBT tests - return the rows not compliant

# packages.yml has to be configured


version: 2
models:
  - name: person
    columns:
      - name: person_id
        tests:
          - unique
          - not_null:
              severity: warn      # set as'error' to stop process
              error_if: '>1'
        meta:
          metrics:
            total_count:
              type: count_distinct
      - name: gender_concept_id
        meta:
          dimension:
            label: "Gender"
            type: text
        tests:
            - dbt_expectations.expect_column_values_to_be_in_set:
                value_set: [8507,8532,0]
                quote_values: false